// User Action
export const USER_LOG_IN_REQUEST = 'USER_LOG_IN_REQUEST';
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS';
export const USER_LOG_IN_FAILURE = 'USER_LOG_IN_FAILURE';
export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE';

export const USER_BUS_MODAL = 'USER_BUS_MODAL';
export const USER_BUS_MODAL_SUCCESS = 'USER_BUS_MODAL_SUCCESS';
export const USER_BUS_MODAL_FAILURE = 'USER_BUS_MODAL';
