POST {{apiUrl}}/block/user
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "blockUserId": 2
}

###
GET {{apiUrl}}/block/users
Authorization: {{authorizationToken}}