POST {{apiUrl}}/post/1/reply
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "content": "감사합니다!"
}

###
PUT {{apiUrl}}/post/reply/1
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "content": "수정!!!"
}

###
DELETE {{apiUrl}}/post/reply/2
Authorization: {{authorizationToken}}