POST {{apiUrl}}/taxi/party
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "placeId": 1,
  "headcount": 3,
  "meetingDate": "2022-05-27T09:00"
}

###
POST {{apiUrl}}/taxi/party/3
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
GET {{apiUrl}}/taxi/parties?placeId=1&date=2022-05-20&page=1&size=10
Authorization: {{authorizationToken}}

###
GET {{apiUrl}}/taxi/my-parties
Authorization: {{authorizationToken}}
