POST {{apiUrl}}/user/signup
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "email": "test131@test.com",
  "studentId": "12345",
  "imageId": 1
}

###
POST {{apiUrl}}/user/email
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "email": "test@test.com"
}

###
POST {{apiUrl}}/user/fcm/token
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "fcmToken": "as123dfzxcv"
}

###
POST {{apiUrl}}/user/email/verification
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "code": "9922748"
}

###
GET {{apiUrl}}/profiles
Authorization: {{authorizationToken}}

###
GET {{apiUrl}}/user
Authorization: {{authorizationToken}}

###
PUT {{apiUrl}}/user
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "imageId": "2"
}

###
DELETE {{apiUrl}}/user
Authorization: {{authorizationToken}}
